#!/bin/sh
#
#       /etc/init.d/hyn
#
# Starts the hyn daemon
#
# chkconfig: 345 95 5
# description: Runs the HYN daemon.
# processname: hyn

#. /etc/init.d/functions

log=/var/log/hyn.log

prog="hyn"
proc=/var/lock/subsys/hyn
bin=/domains/cloudspark.nl/lib/hyn/daemon/daemon.php

start() {
        if [ ! -f $proc ]; then
                echo -n $"Starting $prog: "
                daemon $bin --log=$log
                RETVAL=$?
                [ $RETVAL -eq 0 ] && touch $proc
                echo
        fi
        return $RETVAL
}

stop() {
        echo -n $"Stopping $prog: "
        killproc $bin
        RETVAL=$?
        [ $RETVAL -eq 0 ] && rm -f $proc
        echo
        return $RETVAL
}

restart() {
        stop
        start
}

reload() {
        restart
}

status_at() {
        status $bin
}

case "$1" in
start)
        start
        ;;
stop)
        stop
        ;;
reload|restart)
        restart
        ;;
condrestart)
        if [ -f $proc ]; then
                restart
        fi
        ;;
status)
        status_at
        ;;
*)

echo $"Usage: $0 {start|stop|restart|condrestart|status}"
        exit 1
esac

exit $?
exit $RETVAL
